- hosts: all
  tasks:

  - name: "Copying JDK software"
    copy:
       dest: "/root"
       src: "/root/jdk-8u171-linux-x64.rpm"

  - name:  "Copying Hadoop software"
    copy:
       dest: "/root"
       src: "/root/hadoop-1.2.1-1.x86_64.rpm"
   
  - name: "Installing JDK software"
    command: "rpm -i jdk-8u171-linux-x64.rpm"
    ignore_errors: yes

  - name: "Installing Hadoop Software"
    command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes


- hosts: slave
  vars:
          - direc_nn: /root/task11

  tasks:

  - name: "Creating Data Node Directory"
    file:
        path: "{{ direc_nn }}"
        state: directory

  - name: we are going to Share the HDFS-site.xml file by using the variables
    template:
       src: /root/name-hdfs.txt
       dest: /etc/hadoop/hdfs-site.xml

  - name: Sending Core-site.xml file to the respective directory.
    template:
       src: /root/name-core.txt
       dest: /etc/hadoop/core-site.xml

  - name: "Stopping firewalld"
    command: systemctl stop firewalld

  - name: "Starting Datanode Services"
    command: hadoop-daemon.sh start datanode
  
  - name: "Checking status of Datanode"
    shell: "jps"
    register: jps
  - debug:
       var: jps




- hosts: master
  vars:
          - direc_nn: /root/task11

  tasks:
  - name: "Creating Name Node Directory"
    file:
        path: "{{ direc_nn }}"
        state: directory

  - name: "Configuring hdfs-site.xml"
    blockinfile:
        path: /etc/hadoop/hdfs-site.xml
        insertafter: "<configuration>"
        block:
             <property>
             <name>dfs.name.dir</name>
             <value>{{ direc_nn }}</value>
             </property>

  - name: "Configuring core-site.xml"
    blockinfile:
        path: /etc/hadoop/core-site.xml
        insertafter: "<configuration>"
        block:
             <property>
             <name>fs.default.name</name>
             <value>hdfs://{{ansible_facts["default_ipv4"]["address"]}}:9001</value>
             </property>

  - name: "Formatting namenode"
    shell: "echo Y | hadoop namenode -format"
    register: format
    ignore_errors: yes

  - debug:
        var: format

  - name: "Stopping firewalld"
    command: systemctl stop firewalld

  - name: "Starting namenode Services"
    command: hadoop-daemon.sh start namenode
    ignore_errors: yes
    

  - name: "Checking status of namenode"
    shell: "jps"
    register: jps
  - debug:
        var: jps

  - name: "Checking Hadoop Cluster Report"
    command: hadoop dfsadmin -report
